
ACTIVATIONS = [
    "ReLU",
    "RReLU",
    "PReLU",
    "ELU",
    "Softplus",
    "Tanh",
    "SELU",
    "LeakyReLU",
    "Sigmoid",
    "GELU"
]

LOSSES = [
    "MAPELoss",
    "SMAPELoss",
    "MASELoss",
    "NormalizedDeviationLoss",
    "MSELoss",
    "L1Loss",
    "SmoothL1Loss",
    "BCEWithLogitsLoss",
    "BCELoss",
    "CrossEntropyLoss",
    "NLLLoss",
    "PoissonNLLLoss",
    "KLDivLoss",
    "MarginRankingLoss",
    "HingeEmbeddingLoss",
    "MultiLabelMarginLoss",
    "CosineEmbeddingLoss",
    "MultiMarginLoss",
    "TripletMarginLoss",
    "TripletMarginWithDistanceLoss"
]

OPTIMIZERS = [
  "Adam",
  "SGD",
  "RMSprop",
  "Adagrad",
  "Adadelta",
  "AdamW"
]

BLOCKS = [
  "Generic",
  "BottleneckGeneric",
  "GenericAE",
  "BottleneckGenericAE",
  "GenericAEBackcast",
  "GenericAEBackcastAE",
  "Trend",
  "TrendAE",
  "Seasonality",
  "SeasonalityAE",
  "AutoEncoder",
  "AutoEncoderAE",
  "HaarWavelet",
  "HaarAltWavelet",
  "DB2Wavelet",
  "DB2AltWavelet",
  "DB3Wavelet",
  "DB3AltWavelet",
  "DB4Wavelet",
  "DB4AltWavelet",
  "DB10Wavelet",
  "DB10AltWavelet",
  "DB20AltWavelet",
  "Coif1Wavelet",
  "Coif1AltWavelet",
  "Coif2Wavelet",
  "Coif2AltWavelet",
  "Coif3Wavelet",
  "Coif3AltWavelet",
  "Coif10Wavelet",
  "Coif10AltWavelet",
  "Symlet2Wavelet",
  "Symlet2AltWavelet",
  "Symlet3Wavelet",
  "Symlet10Wavelet",
  "Symlet20Wavelet",
]
